# mash of travis scripts from
# https://github.com/joerick/cibuildwheel/blob/master/.travis.yml
# https://github.com/pypa/python-manylinux-demo/blob/master/.travis.yml
notifications:
  email: false

deploy:
  provider: releases
  api_key:
    secure: VVUpxWmC7VkGcbniATyHZdxo7nMHqT7wYwzJ/lmvDm9IEhxwp2V9Fmra8J1oCRyBhVzbwqSsJzlAlffFu8DtneM6Ye0v4tWQr7Dt0XLICT+B0jz+YGeAQwsDljhNPQ5VsioDlrhoftD3gTBqKBQqMRDcSNwTISPUKZVcvDErBGU=
  file_glob: true
  file: wheelhouse/ecos-*.whl
  skip_cleanup: true
  on:
    branch: master
    tags: true

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
    - sudo: required
      arch: arm64-graviton2
      group: edge
      virt: lxd
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_aarch64
    - os: osx
      env: PYTHON=python3

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull $DOCKER_IMAGE; fi

script:
  - make version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./travis/build-osx-wheels.sh; fi
  - ls wheelhouse/
